---
- name: Ensure ufw package is installed
  ansible.builtin.package:
    name: ufw
    state: present

- name: Set default ufw policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }

- name: Apply UFW rules
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop:
    - { port: '22',    proto: 'tcp', comment: 'Allow SSH access' }
    - { port: '80',    proto: 'tcp', comment: 'Allow HTTP (Caddy)' }
    - { port: '443',   proto: 'tcp', comment: 'Allow HTTPS (Caddy)' }
    - { port: '3022',  proto: 'tcp', comment: 'Forgejo SSH' }
    - { port: '51819', proto: 'tcp', comment: 'wg-access-server' }
    - { port: '51820', proto: 'udp', comment: 'Allow WireGuard VPN' }

- name: Enable ufw
  community.general.ufw:
    state: enabled
