---
- name: Copy Portfolio socket unit to user systemd directory
  ansible.builtin.copy:
    src: "portfolio.socket"
    dest: "~/.config/systemd/user/"

- name: Copy Portfolio container unit to user quadlet directory
  ansible.builtin.copy:
    src: "portfolio.container"
    dest: "~/.config/containers/systemd/"

- name: Reload systemd user daemon to detect new units
  ansible.builtin.systemd:
    scope: user
    daemon_reload: yes

- name: Enable and start Portfolio socket for user
  ansible.builtin.systemd:
    scope: user
    name: portfolio.socket
    enabled: yes
    state: started
