FROM docker.io/rust:alpine as builder
RUN apk add --no-cache build-base musl-dev linux-headers
WORKDIR /usr/src 
RUN cargo install --locked boringtun-cli
FROM alpine:latest
RUN apk add --no-cache iproute2 iptables wireguard-tools \
 && addgroup -S wireguard && adduser -S -G wireguard wireguard
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
COPY --from=builder /usr/local/cargo/bin/boringtun-cli /usr/bin/boringtun
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]