FROM docker.io/donaldzou/wgdashboard:latest
RUN apk add --no-cache socat
COPY entrypoint-dashboard.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]